language: node_js
node_js:
  - 8.12.0
sudo: required
services:
  - docker
env:
  global:
    - CXX=g++-4.8
  matrix:
    - USE_SENTRY=1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - docker pull getsentry/sentry-cli

script:
  - npm install
  - NODE_ENV=production npm run build:dll
  - npm run build

before_deploy:
#  - bash deploy/sentry_release.sh
  - find dist/ -type f -name "*.map" -delete
  - zip -r dist.zip dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rV4MOUd391Qo2g71qPmppbucSkbeOUJqMcgD1XbATsncn9bLE9pvlb6RcsMQQoKo6UFuzbyn+N+COpKxywgr5OD5liMC6jGhBLv/s52R5aOzQGqPFGGBgmPMB/amzJNdj7FxtmrztU8a1KlDlaoeVAe2J78sZBfh9Szpvy7+pWIuXBWaod+mpNwZvQPMoWNgy/U0hgetgaARQUYFntbtG59e3LVlI43kCTPcU+4I9ZKXA3fWWHdDui3G/cfOTnqu5/btn7MVo4S4nnc1Vry5vz3MAQv/xkpZk7UOWe+ctcLC9TSHigGFkCRcd5qxRbk5n8g8wOu1w/waZ5Q9MvzG9xbVkQ9xr728BUTj3o7Ds+u/4hnEKCaFaoKqMaPeCRzhx9t3euQF66JrUO7GqvIQmPpobcHcOb2e4PW0d5sVTfUwxnKgHyyeT5orwu3jcpegmV9s7DD3Yk9Jph39m9VAy+05Yf/lOgTvT7TNSGakBETxEDR5l8q9nI20FCl18k8jFIM7XprcF6tAIiLs+Abwf6WsWUJLvlPkVyABJD9wCpIG44z9tNaHyRT+TFdyZ7VnYBQKoNkH5pm0guMfNxQnCXxG6C//SXMU7Vh0XLHgN/9tkHt5wWIxyTVSmcos4RFRuQMD23UTc8IYysBayzJtXXapwMWyPY/Ki20Ac4vxiLk=
  file: dist.zip
  on:
    repo: yuanmabiji/OnlineJudgeFE
    all_branches: true
    tags: true